<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ApplicationSonataUserBundleEntityGrouppaProxy extends \Application\Sonata\UserBundle\Entity\Grouppa implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setGrName($grName)
    {
        $this->__load();
        return parent::setGrName($grName);
    }

    public function getGrName()
    {
        $this->__load();
        return parent::getGrName();
    }

    public function setKurs($kurs)
    {
        $this->__load();
        return parent::setKurs($kurs);
    }

    public function getKurs()
    {
        $this->__load();
        return parent::getKurs();
    }

    public function setSemestr($semestr)
    {
        $this->__load();
        return parent::setSemestr($semestr);
    }

    public function getSemestr()
    {
        $this->__load();
        return parent::getSemestr();
    }

    public function setSpec(\Application\Sonata\UserBundle\Entity\Spec $spec)
    {
        $this->__load();
        return parent::setSpec($spec);
    }

    public function getSpec()
    {
        $this->__load();
        return parent::getSpec();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'grName', 'kurs', 'semestr', 'spec');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}